qat_configuration:
  method: QAT
  select:
    target_types:
    - linear
    - conv2d
    - conv1d
    target_names: []
    exclude_types: []
    exclude_names: []
  function:
    epsilon: 1.0e-05
    weight_function: weight_quant_uniform_symmetric_absmax_per_block_int4
    w_block_size: 128
    is_w_quantized: false
    activation_function: state_quant_uniform_symmetric_absmax_per_block_int8
    a_block_size: 128
    kv_cache_function: ''
    kv_block_size: -1
  training: all
kd_configuration:
  method: KD
  loss_task_alpha: 1.0
  loss_1:
    loss_type: logits
    alpha: 0.7
    loss_function: compute_kld_confidence
    padding_id: -100
    is_router_logits: False
    reduction: batch_mean
    temperature: 2.0
    use_entropy: true
